@startuml
"Administrador" as admin
"Psicologa" as psi
"Paciente" as paci
"Usuário do Sistema" as user

"Cadastrar informações pessoais" as (cad)
"Marcar consulta" as (mar)
"Gerenciar consultas" as (gerenciarConsultas)
"Remarcar consulta" as (rem)
"Desmarcar consulta" as (desm)
"Verificar horários disponíveis" as (verificarHorarios)
"Verificar dados psicólogo" as (verificarPsico)
"Verificar dados paciente" as (verificarPaciente)
"Verificar pacientes marcados" as (verificarMarcados)
"Cadastrar horarios disponíveis" as (hor)

admin --> (Gerar relatórios da plataforma)
admin --> (Receber feedbacks da plataforma)
admin --> (Gerenciar perfis de usuário)

(Gerenciar perfis de usuário) --> (cad)
(Gerenciar perfis de usuário) --> (hor)

user <|-- psi
user <|-- paci



(gerenciarConsultas) <-u- user


(rem) .u. (gerenciarConsultas) : <<extend>>
(desm) .u. (gerenciarConsultas) : <<extend>>
(mar) .u. (gerenciarConsultas) : <<extend>>
(rem) .u. (Contatar paciente) : <<extend>>
(verificarHorarios) .u. (gerenciarConsultas) : <<extend>>

psi -d-> (Contatar paciente)

(rem) .. (verificarHorarios) : <<include>>
(mar) .down. (verificarHorarios) : <<include>> 

psi -d-> (verificarPaciente)
psi -d-> (verificarMarcados)
paci -d-> (verificarPsico)
@enduml