@startuml classes

abstract class Usuario {
  - nome: str
  # email: str
  # telefone: str
  # senha: str
  # cpf: str
}


class Paciente {
  - data_nascimento: date
  # numero_USP: str
 
}

class Psicologo {
  # registro_profissional: str
  - abordagem: str
}

class Consulta {
  - paciente: Paciente
  - psicologo: Psicologo
  - horario: Horario
  - status: str
}

class Horario {
  - data: int
  - dia_semana: DiaSemana
  - mes: Mes
  - hora_inicio: Hora
  - hora_fim: Hora
  - disponivel: bool
  
}

enum DiaSemana {
  SEGUNDA,
  TERCA,
  QUARTA,
  QUINTA,
  SEXTA
}

enum Mes {
  JANEIRO,
  FEVEREIRO,
  MARCO,
  ABRIL,
  MAIO,
  JUNHO,
  JULHO,
  AGOSTO,
  SETEMBRO,
  OUTUBRO,
  NOVEMBRO,
  DEZEMBRO
}

enum Hora {
  H08_00,
  H09_00,
  H10_00,
  H11_00,
  H12_00,
  H13_00,
  H14_00,
  H15_00,
  H16_00,
  H17_00,
  H18_00,
  H19_00
}

class Administrador {
  - cargo: str
}

Usuario <|-- Paciente
Usuario <|-- Psicologo
Usuario <|-- Administrador
Paciente --> "0..*" Consulta 
Psicologo --> "0..*" Consulta
Consulta --> "1..1" Horario

@enduml
