@startuml mvc_diagram

skinparam component {
  backgroundColor<<consultas>> LightBlue
  backgroundColor<<pacientes>> LightGreen
  backgroundColor<<usuarios>> LightPink
  backgroundColor<<administracao>> Orchid
  backgroundColor<<model>> LightGray
  backgroundColor<<database>> Thistle
}

skinparam Arrow {
  Padding 10
  Thickness 2
}

package "View" {
  [<<view>> Gerenciamento de Consultas] <<consultas>>
  [<<view>> Acesso a Informações de Pacientes e Psicólogos] <<pacientes>>
  [<<view>> Cadastro e Acesso de Usuários] <<usuarios>>
  [<<view>> Administração da Plataforma] <<administracao>>
}

package "Controller" {
  [<<controller>> Gerenciamento de Consultas] <<consultas>>
  [<<controller>> Acesso a Informações de Pacientes e Psicólogos] <<pacientes>>
  [<<controller>> Cadastro e Acesso de Usuários] <<usuarios>>
  [<<controller>> Administração da Plataforma] <<administracao>>
}

package "Model" <<model>> {
  [Componente de Acesso a Dados do Usuário]
  [Componente de Acesso a DB de Agenda]
}

database "BD" <<database>> {
  [Base de dados Usuário]
  [Base de dados Agenda]
}

' Posicionamento dos pacotes para alinhar horizontalmente
View -[hidden]-> Controller
Controller -[hidden]-> Model
Model -[hidden]-> BD

' Relacionamentos entre packages com setas ajustadas
View --> Controller : aciona
Controller --> View : atualiza
Controller --> Model : atualiza
Model --> Controller : notifica
Model <--> BD : CRUD acessa

@enduml
