# Generated by Django 5.1.4 on 2024-12-12 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("telefone", models.CharField(max_length=15)),
                ("senha", models.CharField(max_length=20)),
                ("cpf", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_da_semana",
                    models.CharField(
                        choices=[
                            ("SEGUNDA", "Segunda-feira"),
                            ("TERCA", "Terça-feira"),
                            ("QUARTA", "Quarta-feira"),
                            ("QUINTA", "Quinta-feira"),
                            ("SEXTA", "Sexta-feira"),
                            ("SABADO", "Sábado"),
                            ("DOMINGO", "Domingo"),
                        ],
                        default="SEGUNDA",
                        max_length=20,
                    ),
                ),
                ("data", models.DateField()),
                (
                    "mes",
                    models.CharField(
                        choices=[
                            ("JANEIRO", "Janeiro"),
                            ("FEVEREIRO", "Fevereiro"),
                            ("MARCO", "Março"),
                            ("ABRIL", "Abril"),
                            ("MAIO", "Maio"),
                            ("JUNHO", "Junho"),
                            ("JULHO", "Julho"),
                            ("AGOSTO", "Agosto"),
                            ("SETEMBRO", "Setembro"),
                            ("OUTUBRO", "Outubro"),
                            ("NOVEMBRO", "Novembro"),
                            ("DEZEMBRO", "Dezembro"),
                        ],
                        default="JANEIRO",
                        max_length=20,
                    ),
                ),
                (
                    "hora_inicio",
                    models.CharField(
                        choices=[("H00_00", "0h00")], default="H00_00", max_length=20
                    ),
                ),
                (
                    "hora_fim",
                    models.CharField(
                        choices=[("H00_00", "0h00")], default="H00_00", max_length=20
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Administrador",
            fields=[
                (
                    "usuario_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="usuarios.usuario",
                    ),
                ),
                ("cargo", models.CharField(max_length=100)),
            ],
            bases=("usuarios.usuario",),
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "usuario_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="usuarios.usuario",
                    ),
                ),
                ("data_nascimento", models.DateField()),
                ("numero_usp", models.CharField(max_length=10)),
            ],
            bases=("usuarios.usuario",),
        ),
        migrations.CreateModel(
            name="Psicologo",
            fields=[
                (
                    "usuario_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="usuarios.usuario",
                    ),
                ),
                ("registro_profissional", models.CharField(max_length=100)),
                ("abordagem", models.CharField(max_length=100)),
            ],
            bases=("usuarios.usuario",),
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "horario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consulta",
                        to="usuarios.horario",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas",
                        to="usuarios.paciente",
                    ),
                ),
                (
                    "psicologo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas",
                        to="usuarios.psicologo",
                    ),
                ),
            ],
        ),
    ]
