# Generated by Django 5.1 on 2024-12-14 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_consulta_horario_remove_consulta_paciente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.CharField(choices=[('SEGUNDA', 'Segunda-feira'), ('TERCA', 'Terça-feira'), ('QUARTA', 'Quarta-feira'), ('QUINTA', 'Quinta-feira'), ('SEXTA', 'Sexta-feira'), ('SABADO', 'Sábado'), ('DOMINGO', 'Domingo')], default='SEGUNDA', max_length=20)),
                ('data', models.DateField()),
                ('hora_inicio', models.CharField(choices=[('H00_00', '0:00'), ('H01_00', '1:00'), ('H02_00', '2:00'), ('H03_00', '3:00'), ('H04_00', '4:00'), ('H05_00', '5:00'), ('H06_00', '6:00'), ('H07_00', '7:00'), ('H08_00', '8:00'), ('H09_00', '9:00'), ('H10_00', '10:00'), ('H11_00', '11:00'), ('H12_00', '12:00'), ('H13_00', '13:00'), ('H14_00', '14:00'), ('H15_00', '15:00'), ('H16_00', '16:00'), ('H17_00', '17:00'), ('H18_00', '18:00'), ('H19_00', '19:00'), ('H20_00', '20:00'), ('H21_00', '21:00'), ('H22_00', '22:00'), ('H23_00', '23:00')], max_length=20)),
                ('hora_fim', models.CharField(choices=[('H00_00', '0:00'), ('H01_00', '1:00'), ('H02_00', '2:00'), ('H03_00', '3:00'), ('H04_00', '4:00'), ('H05_00', '5:00'), ('H06_00', '6:00'), ('H07_00', '7:00'), ('H08_00', '8:00'), ('H09_00', '9:00'), ('H10_00', '10:00'), ('H11_00', '11:00'), ('H12_00', '12:00'), ('H13_00', '13:00'), ('H14_00', '14:00'), ('H15_00', '15:00'), ('H16_00', '16:00'), ('H17_00', '17:00'), ('H18_00', '18:00'), ('H19_00', '19:00'), ('H20_00', '20:00'), ('H21_00', '21:00'), ('H22_00', '22:00'), ('H23_00', '23:00')], max_length=20)),
                ('disponivel', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios', to='usuarios.paciente')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='usuarios.psicologo')),
            ],
        ),
    ]
