# Generated by Django 5.1 on 2024-12-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_horario_hora_fim_alter_horario_hora_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='dia_da_semana',
        ),
    ]
